version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: cargo
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: pip
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
      day: "friday"
