[package]
name = "python-launcher"
description = "The Python launcher for UNIX"
version = "0.5.0"
authors = ["Brett Cannon <brett@python.org>"]
repository = "https://github.com/brettcannon/python-launcher"
readme = "README.md"
license = "MIT"
keywords = ["Python"]
categories = ["command-line-utilities"]

[badges]
travis-ci = { repository = "brettcannon/python-launcher" }
maintenance = { status = "experimental" }

[dependencies]
nix = "0.11.0"

[[bin]]
name = "py"
path = "src/main.rs"
