contact_links:
  - name: Feature Request
    url: https://github.com/brettcannon/python-launcher/discussions/categories/ideas
    about: Open an "Ideas" discussion
  - name: Help
    url: https://github.com/brettcannon/python-launcher/discussions/categories/q-a
    about: Open a "Q&A" discussion
