name: Continuous Integration

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Run unit and system tests
      run: cargo test --verbose

    - name: Install Python dependencies
      run: python -m pip install -r dev-requirements.txt

    - name: Run `main.rs` tests
      # Requires a debug build of `py` exists.
      run: python -m pytest test_main.py

  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v1

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run coverage
      run: cargo tarpaulin -v --out Xml

    - name: Upload to codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: "3f48ed0d-a74b-45d6-ac98-025b350a4779"

  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: rustup component add clippy

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings


  format-check:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        rustup component add rustfmt
        python -m pip install black

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Run Black
      run: python -m black --check --target-version py37 .

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit
        run: cargo audit --deny-warnings
